version = 0.1

[default.deploy.parameters]
stack_name = "expense-tracker-stack"
resolve_s3 = true
s3_prefix = "expense-tracker-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
